#!/bin/sh

# Run me after generating documentation from Enterprise Architect.
# I will add a link to the static "overview.html" file at the start of the TOC.

tocFile=./docs/toc.htm
tmpFile=`basename $0`.$$.tmp

sed "s/^\(<body onload=\"tocInit()\">\)/<!-- BEGIN MODIFICATIONS --> \n<!-- \1 --> \n<body><a href=\"overview.html\" target=\"cont\"><font size=\"+1\">Model Overview<\/font><\/a> \n<script language=\"JavaScript\"> \n tocInit(); \n<\/script> \n<!-- END MODIFICATIONS --> /g" $tocFile >> $tmpFile

mv $tmpFile $tocFile
