ID = 'cmip6.atmosphere.gravity_waves'

TYPE = 'science.process'

CIM = '2.0'

CONTACT = 'Charlotte Pascoe'

AUTHORS = ''

DATE = ''

VERSION = '0.9'

# ====================================================================
# PROPERTIES
# ====================================================================
PROPERTIES = {

    # ----------------------------------------------------------------
    # MANIFEST
    # ----------------------------------------------------------------
    'short_name': 'Atmosphere gravity waves',
    'description': 'Characteristics of the parameterised gravity waves in the atmosphere, whether from orography or other sources.',
    
    'details': [('sponge_layer',
                 'attributes'),
                ('background',
                 'attributes'),
                ('subgrid_scale_orography',
                 'attributes'),
            ],
    
    'sub_process': ['orographic_gravity_waves',
                    'non_orographic_gravity_waves',
                ],
    
    # ----------------------------------------------------------------
    # DETAILS
    # ----------------------------------------------------------------
    'sponge_layer': {
        'short_name': 'Gravty waves sponge layer',
        'description': 'Sponge layer in the upper levels in order to avoid gravity wave reflection at the top.',
        'attributes': (
            'ENUM:gravity_waves_sponge_layer_attributes', '1.1', 
            'Gravity waves sponge layer'), 
    },

    'background': {
        'short_name': 'Gravity waves background',
        'description': 'Background distribution of waves.',
        'attributes': (
            'ENUM:gravity_waves_background_attributes', '1.1',
            'Background wave distribution'),
    },

    'subgrid_scale_orography':  {
        'short_name': 'Gravity waves subgrid scale orography',
        'description': 'Subgrid scale orography effects taken into account.',
        'attributes': (
            'ENUM:gravity_waves_subgrid_scale_orography_attributes', '1.N',
            'Subgrid-scale orography'),
    },

    # ----------------------------------------------------------------
    # SUB-PROCESSES
    # ----------------------------------------------------------------
    'orographic_gravity_waves': {
        'short_name': 'Orographic gravity waves',
        'description': 'Gravity waves generated due to the presence of orography',
        'details': [('orographic_gravity_waves_details',
                     'source_mechanisms', 'calculation_method', 'propagation_scheme', 'dissipation_scheme'),
                ],
    },

    'non_orographic_gravity_waves': {
        'short_name': 'Non-orographic gravity waves',
        'description': 'Gravity waves generated by non-orographic processes.',
        'details': [('non_orographic_gravity_waves_details',
                     'source_mechanisms', 'calculation_method', 'propagation_scheme', 'dissipation_scheme'),
                ],
    },

    # ----------------------------------------------------------------
    # SUB-PROCESS DETAILS
    # ----------------------------------------------------------------
    'orographic_gravity_waves_details': {
        'short_name': '',
        'description': '',
        'source_mechanisms': (
            'ENUM:orographic_gravity_waves_source_mechanisms', '1.N',
            'Orographic gravity wave source mechanisms'),
        'calculation_method': (
            'ENUM:orographic_gravity_waves_calculation_method', '1.N',
            'Orographic gravity wave calculation method'),
        'propagation_scheme': (
            'ENUM:orographic_gravity_waves_propagation_scheme', '1.1',
            'Orographic gravity wave propogation scheme'),
        'dissipation_scheme': (
            'ENUM:orographic_gravity_waves_dissipation_scheme', '1.1',
                    'Orographic gravity wave dissipation scheme'),
    },

    'non_orographic_gravity_waves_details': {
        'short_name': '',
        'description': '',                
        'source_mechanisms': (
            'ENUM:non_orographic_gravity_waves_source_mechanisms', '1.N',
            'Non-orographic gravity wave source mechanisms'),
        'calculation_method': (
            'ENUM:non_orographic_gravity_waves_calculation_method', '1.N',
            'Non-orographic gravity wave calculation method'),
        'propagation_scheme': (
            'ENUM:non_orographic_gravity_waves_propagation_scheme', '1.1',
            'Non-orographic gravity wave propogation scheme'),
        'dissipation_scheme': (
            'ENUM:non_orographic_gravity_waves_dissipation_scheme', '1.1',
                    'Non-orographic gravity wave dissipation scheme'),
    },
              
}

# ====================================================================
# ENUMERATIONS
# ====================================================================
ENUMERATIONS = {

    'gravity_waves_sponge_layer_attributes': {
        'short_name': 'Gravity waves sponge layer attributes',
        'description': 'Gravity waves sponge layer attributes',
        'members': [
            ('None', None),
            ('Other', None),
        ]
    },

    'gravity_waves_background_attributes': {
        'short_name': 'Gravity waves background attributes',
        'description': 'Gravity waves background attributes',
        'members': [
            ('None', None),
            ('Other', None),
        ]
    },

    'gravity_waves_subgrid_scale_orography_attributes': {
        'short_name': 'Gravity waves subgrid scale orography attributes',
        'description': 'Gravity waves subgrid scale orography attributes',
        'members': [
            ('effect on drag', None),
            ('effect on lifting', None),
            ('Other', None),
        ]
    },

    'orographic_gravity_wave_source_mechanisms': {
        'short_name': 'Orographic gravity wave source mechanisms',
        'description': 'Physical mechanisms generatic orographic gravity waves.',
        'members': [
            ('linear mountain waves', None),
            ('hydraulic jump', None),
            ('envelope orography', None),
            ('statistical sub-grid scale variance', None),
            ('other', None),
        ]
    },

    'orographic_gravity_wave_calculation_method': {
        'short_name': 'Orographic gravity wave calculation method',        
        'description': 'Calculation method for orographic gravity waves.',
        'members': [
            ('non-linear calculation', None),
            ('more than two cardinal directions', None),
        ]
    },

    'orographic_gravity_wave_propagation_scheme': {
        'short_name': 'Orographic gravity wave propagation scheme', 
        'description': 'Type of propagation scheme for orgraphic gravity waves',
        'members': [
            ('linear theory', None),
            ('non-linear theory', None),
            ('other', None),
        ]
    },

    'orographic_gravity_wave_dissipation_scheme': {
        'short_name': 'Orographic gravity wave dissipation scheme',
        'description': 'Type of dissipation scheme for orographic gravity waves.',
        'members': [
            ('total wave', None),
            ('single wave', None),
            ('spectral', None),
            ('linear', None), 
            ('other', None),
        ]
    },

    'non_orographic_gravity_wave_source_mechanisms': {
        'short_name': 'Non-orographic gravity wave source mechanisms', 
        'description': 'Physical mechanisms generating non-orographic gravity waves',
        'members': [
            ('convection', None),
            ('precipitation', None),
            ('background spectrum', None),
            ('other', None),
        ]
    },

    'non_orographic_gravity_wave_calculation_method': {
        'short_name': 'Non-orographic gravity wave calculation method', 
        'description': 'Calculation method for non-orographic gravity waves',
        'members': [
            ('spatially dependent', None),
            ('temporally dependent', None),
            ]
    },

    'non_orographic_gravity_wave_propagation_scheme': {
        'short_name': 'Non-orographic gravity wave propagation scheme',
        'description': 'Type of propagation scheme for non-orographic gravity waves.',
        'members': [
            ('linear theory', None),
            ('non-linear theory', None),
            ('other', None),
        ]
    },

    'non_orographic_gravity_wave_dissipation_scheme': {
        'short_name': 'Non-orographic gravity wave dissipation scheme', 
        'description': 'Type of dissipation scheme for non-orographic gravity waves.',
        'members': [
            ('total wave', None),
            ('single wave', None),
            ('spectral', None),
            ('linear', None), 
            ('other', None),
        ]
    },

}
